### PR TITLE
Why is this not in core?

### PR DESCRIPTION
**Pull request by melvyn-sopacua**
IONO

### CODE REVIEW

**Comment by blueyed** [comment]
You should rather have a global PYTHONSTARTUP yourself, e.g. https://github.com/blueyed/dotfiles/blob/master/config/python/pythonrc.py.

**Comment by melvyn-sopacua** [comment]
Wow, learn something new every day. After >5 years of python, never investigated/found that.

So, I'll clean it up and see if I can make it so that if the user doesn't have it configured this is launched. Then either throw it away or merge :D.

**Comment by blueyed** [comment]
IMHO it does not make sense to have something custom like that in an example app.

btw: do you know `shell_plus`? https://django-extensions.readthedocs.io/en/latest/shell_plus.html

**Comment by melvyn-sopacua** [comment]
I do and you're right. Doesn't belong here.

**Comment by jpic** [comment]
Lol, I liked it ^^ We could even have added tab-completion with it.


If PYTHONSTARTUP is defined in os.environ ok, let's perhaps not do it, but if PYTHONSTARTUP doesn't exist, then perhaps yes, I think tab completion and history would be great to have in a shell OOTB in 2017 ^^

Perhaps we could stick it in src/crudlfap_conf/pythonstartup and call it from settings ?

**Pull request closed without merging**
