### PR TITLE
Add optional dep [rebased on working ci & shared branch]

### PR DESCRIPTION
**Pull request by jpic**
This is a local branch for #1 which I have created, after rebasing a [passing master](https://travis-ci.org/yourlabs/crudlfap/builds/294512613).

@melvyn-sopacua I have added you to the org so you should be able to do branches on this repo if you want (recommended so we can contribute to them more easily).

### CODE REVIEW

**Comment by melvyn-sopacua** [comment]
Erm, what does too complex mean? Do the type hints screw up flake 8?

**Comment by jpic** [comment]
It's static analysis for code complexity, it checks the number of control operators and things like that, it would like a little refactor, do you think it's possible to split this into smaller units and test them ? Otherwise, just increase the complexity cap [here](https://github.com/yourlabs/crudlfap/blob/master/tox.ini#L26-L29)

**Comment by melvyn-sopacua** [comment]
Refactored a bit, but dropping below 7 would make it silly and effectively more complex. Pushing this to my master, so you can review on #1, then setting up local repo for yourlabs.

**Comment by jpic** [comment]
I have pushed a commit with a proposal for style:

- split add_optional_dep into two functions: has_module and insert_dep_to
- use dep_ as prefix for all functions for consistency, resulting in three functions: dep_importable(), dep_insert_to(), and dep_optional_add() which combines both.
- increased max complexity on this file to 7, like for the other scripts.

What do you think of this proposal ?

**Comment by jpic** [comment]
It would be great to have better function names, but I think we can at list keep the spirit of the code split. If we're going to have more functions in this file I really like if we can sort of namespace them with a prefix like dep_ though if that's possible.

**Comment by melvyn-sopacua** [comment]
I'm thinking we should reduce all this to:

```python
from crudflap.conf import install_optional

OPTIONAL_APPS = {}
OPTIONAL_MIDDLEWARE = {}

install_optional(OPTIONAL_APPS)
install_optional(OPTIONAL_MIDDLEWARE, MIDDLEWARE)
```
I'll go with whatever prefixing you want, but if separated into module, there's little use for it.

For tonight though, I'm calling it quits as I'll be up in at 4am (same timezone).

**Comment by jpic** [comment]
Yeah, much better than repeating the same method call over and over manually !

**Comment by blueyed** [comment]
@jpic 
JFI: you are able to push PR branches by default.  (if the author allows maintainer edits, checkbox in the lower right of a PR).

**Pull request closed without merging**
